apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mssql
  labels:
    app: mssql
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
      - name: mssql
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.service.port }}
        securityContext:
          runAsUser: {{ .Values.securityContext.runAsUser }}
          runAsGroup: {{ .Values.securityContext.runAsGroup }}
        env:
        - name: ACCEPT_EULA
          value: "{{ .Values.env.ACCEPT_EULA }}"
        - name: MSSQL_SA_PASSWORD
          value: {{ .Values.env.MSSQL_SA_PASSWORD }}
        - name: MSSQL_PID
          value: {{ .Values.env.MSSQL_PID }}
      hostname: mssql

