apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mssql
  labels:
    app: mssql
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
      - name: mssql
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.service.port }}
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          value: "Diamanti@111"
        - name: MSSQL_PID
          value: "Evaluation"
      hostname: mssql

