# Default values for sqlpreview.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: mcr.microsoft.com/mssql/server
  tag: 2022-preview-ubuntu-22.04
  pullPolicy: IfNotPresent

service:
  name: mssql
  port: 1433

env:
  ACCEPT_EULA: "Y"
  MSSQL_SA_PASSWORD: "Diamanti@111"
  MSSQL_PID: "Evaluation"

